# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test config

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: oracle
          java-package: jdk
      - name: Install dependencies
        run: poetry install
      - name: Generate repo
        run: |
          echo "GITHUB_TOKEN = ${{ github.token }}" >> ".env"
          poetry run python main.py
      - name: Upload repo
        uses: actions/upload-artifact@v4.3.1
        with:
          name: repo
          path: repo.*
          retention-days: 90
      - name: Upload repo_mapping
        uses: actions/upload-artifact@v4.3.1
        with:
          name: repo_mapping
          path: repo_mapping.*
          retention-days: 90
      - name: Upload logs
        uses: actions/upload-artifact@v4.3.1
        with:
          name: main.log
          path: main.log
          retention-days: 90
  